// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: interview.sql

package sqlgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeArea = `-- name: CompleteArea :exec
UPDATE question_areas
SET status = 'complete', area_ended_at = now()
WHERE session_code = $1 AND area = $2
`

type CompleteAreaParams struct {
	SessionCode string `json:"session_code"`
	Area        string `json:"area"`
}

func (q *Queries) CompleteArea(ctx context.Context, arg CompleteAreaParams) error {
	_, err := q.db.Exec(ctx, completeArea, arg.SessionCode, arg.Area)
	return err
}

const createQuestionArea = `-- name: CreateQuestionArea :one

INSERT INTO question_areas (session_code, area)
VALUES ($1, $2)
ON CONFLICT (session_code, area) DO NOTHING
RETURNING id, session_code, area, status, questions_count, area_started_at, area_ended_at, pre_addressed_evidence
`

type CreateQuestionAreaParams struct {
	SessionCode string `json:"session_code"`
	Area        string `json:"area"`
}

// Queries for interview tables (question_areas + answers).
func (q *Queries) CreateQuestionArea(ctx context.Context, arg CreateQuestionAreaParams) (QuestionArea, error) {
	row := q.db.QueryRow(ctx, createQuestionArea, arg.SessionCode, arg.Area)
	var i QuestionArea
	err := row.Scan(
		&i.ID,
		&i.SessionCode,
		&i.Area,
		&i.Status,
		&i.QuestionsCount,
		&i.AreaStartedAt,
		&i.AreaEndedAt,
		&i.PreAddressedEvidence,
	)
	return i, err
}

const getAnswerCount = `-- name: GetAnswerCount :one
SELECT count(*) FROM answers WHERE session_code = $1
`

func (q *Queries) GetAnswerCount(ctx context.Context, sessionCode string) (int64, error) {
	row := q.db.QueryRow(ctx, getAnswerCount, sessionCode)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getAnswersBySession = `-- name: GetAnswersBySession :many
SELECT id, session_code, area, question_text, audio_urls, transcript_es, transcript_en, ai_evaluation, sufficiency, flags, created_at FROM answers WHERE session_code = $1 ORDER BY created_at
`

func (q *Queries) GetAnswersBySession(ctx context.Context, sessionCode string) ([]Answer, error) {
	rows, err := q.db.Query(ctx, getAnswersBySession, sessionCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Answer{}
	for rows.Next() {
		var i Answer
		if err := rows.Scan(
			&i.ID,
			&i.SessionCode,
			&i.Area,
			&i.QuestionText,
			&i.AudioUrls,
			&i.TranscriptEs,
			&i.TranscriptEn,
			&i.AiEvaluation,
			&i.Sufficiency,
			&i.Flags,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAreasBySession = `-- name: GetAreasBySession :many
SELECT id, session_code, area, status, questions_count, area_started_at, area_ended_at, pre_addressed_evidence FROM question_areas
WHERE session_code = $1
ORDER BY area_started_at
`

func (q *Queries) GetAreasBySession(ctx context.Context, sessionCode string) ([]QuestionArea, error) {
	rows, err := q.db.Query(ctx, getAreasBySession, sessionCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []QuestionArea{}
	for rows.Next() {
		var i QuestionArea
		if err := rows.Scan(
			&i.ID,
			&i.SessionCode,
			&i.Area,
			&i.Status,
			&i.QuestionsCount,
			&i.AreaStartedAt,
			&i.AreaEndedAt,
			&i.PreAddressedEvidence,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getInProgressArea = `-- name: GetInProgressArea :one
SELECT id, session_code, area, status, questions_count, area_started_at, area_ended_at, pre_addressed_evidence FROM question_areas
WHERE session_code = $1 AND status = 'in_progress'
LIMIT 1
`

func (q *Queries) GetInProgressArea(ctx context.Context, sessionCode string) (QuestionArea, error) {
	row := q.db.QueryRow(ctx, getInProgressArea, sessionCode)
	var i QuestionArea
	err := row.Scan(
		&i.ID,
		&i.SessionCode,
		&i.Area,
		&i.Status,
		&i.QuestionsCount,
		&i.AreaStartedAt,
		&i.AreaEndedAt,
		&i.PreAddressedEvidence,
	)
	return i, err
}

const incrementAreaQuestions = `-- name: IncrementAreaQuestions :exec
UPDATE question_areas
SET questions_count = questions_count + 1
WHERE session_code = $1 AND area = $2
`

type IncrementAreaQuestionsParams struct {
	SessionCode string `json:"session_code"`
	Area        string `json:"area"`
}

func (q *Queries) IncrementAreaQuestions(ctx context.Context, arg IncrementAreaQuestionsParams) error {
	_, err := q.db.Exec(ctx, incrementAreaQuestions, arg.SessionCode, arg.Area)
	return err
}

const markAreaInsufficient = `-- name: MarkAreaInsufficient :exec
UPDATE question_areas
SET status = 'insufficient', area_ended_at = now()
WHERE session_code = $1 AND area = $2
`

type MarkAreaInsufficientParams struct {
	SessionCode string `json:"session_code"`
	Area        string `json:"area"`
}

func (q *Queries) MarkAreaInsufficient(ctx context.Context, arg MarkAreaInsufficientParams) error {
	_, err := q.db.Exec(ctx, markAreaInsufficient, arg.SessionCode, arg.Area)
	return err
}

const markAreaNotAssessed = `-- name: MarkAreaNotAssessed :exec
UPDATE question_areas
SET status = 'not_assessed', area_ended_at = now()
WHERE session_code = $1 AND area = $2 AND status IN ('pending', 'pre_addressed')
`

type MarkAreaNotAssessedParams struct {
	SessionCode string `json:"session_code"`
	Area        string `json:"area"`
}

func (q *Queries) MarkAreaNotAssessed(ctx context.Context, arg MarkAreaNotAssessedParams) error {
	_, err := q.db.Exec(ctx, markAreaNotAssessed, arg.SessionCode, arg.Area)
	return err
}

const markAreaPreAddressed = `-- name: MarkAreaPreAddressed :exec
UPDATE question_areas
SET status = 'pre_addressed', pre_addressed_evidence = $3
WHERE session_code = $1 AND LOWER(area) = LOWER($2) AND status = 'pending'
`

type MarkAreaPreAddressedParams struct {
	SessionCode          string      `json:"session_code"`
	Lower                string      `json:"lower"`
	PreAddressedEvidence pgtype.Text `json:"pre_addressed_evidence"`
}

func (q *Queries) MarkAreaPreAddressed(ctx context.Context, arg MarkAreaPreAddressedParams) error {
	_, err := q.db.Exec(ctx, markAreaPreAddressed, arg.SessionCode, arg.Lower, arg.PreAddressedEvidence)
	return err
}

const saveAnswer = `-- name: SaveAnswer :one
INSERT INTO answers (session_code, area, question_text, audio_urls, transcript_es, transcript_en, ai_evaluation, sufficiency, flags)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, session_code, area, question_text, audio_urls, transcript_es, transcript_en, ai_evaluation, sufficiency, flags, created_at
`

type SaveAnswerParams struct {
	SessionCode  string      `json:"session_code"`
	Area         string      `json:"area"`
	QuestionText pgtype.Text `json:"question_text"`
	AudioUrls    []byte      `json:"audio_urls"`
	TranscriptEs pgtype.Text `json:"transcript_es"`
	TranscriptEn pgtype.Text `json:"transcript_en"`
	AiEvaluation []byte      `json:"ai_evaluation"`
	Sufficiency  pgtype.Text `json:"sufficiency"`
	Flags        []byte      `json:"flags"`
}

func (q *Queries) SaveAnswer(ctx context.Context, arg SaveAnswerParams) (Answer, error) {
	row := q.db.QueryRow(ctx, saveAnswer,
		arg.SessionCode,
		arg.Area,
		arg.QuestionText,
		arg.AudioUrls,
		arg.TranscriptEs,
		arg.TranscriptEn,
		arg.AiEvaluation,
		arg.Sufficiency,
		arg.Flags,
	)
	var i Answer
	err := row.Scan(
		&i.ID,
		&i.SessionCode,
		&i.Area,
		&i.QuestionText,
		&i.AudioUrls,
		&i.TranscriptEs,
		&i.TranscriptEn,
		&i.AiEvaluation,
		&i.Sufficiency,
		&i.Flags,
		&i.CreatedAt,
	)
	return i, err
}

const setAreaInProgress = `-- name: SetAreaInProgress :exec
UPDATE question_areas
SET status = 'in_progress', area_started_at = now()
WHERE session_code = $1 AND area = $2 AND status IN ('pending', 'pre_addressed')
`

type SetAreaInProgressParams struct {
	SessionCode string `json:"session_code"`
	Area        string `json:"area"`
}

func (q *Queries) SetAreaInProgress(ctx context.Context, arg SetAreaInProgressParams) error {
	_, err := q.db.Exec(ctx, setAreaInProgress, arg.SessionCode, arg.Area)
	return err
}
