// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Coupon struct {
	ID          pgtype.UUID        `json:"id"`
	Code        string             `json:"code"`
	MaxUses     int32              `json:"max_uses"`
	CurrentUses int32              `json:"current_uses"`
	DiscountPct int32              `json:"discount_pct"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	Source      pgtype.Text        `json:"source"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Session struct {
	SessionCode  string             `json:"session_code"`
	PinHash      string             `json:"pin_hash"`
	Track        pgtype.Text        `json:"track"`
	Status       string             `json:"status"`
	Role         string             `json:"role"`
	TimerSeconds int32              `json:"timer_seconds"`
	StartedAt    pgtype.Timestamptz `json:"started_at"`
	EndedAt      pgtype.Timestamptz `json:"ended_at"`
	PaymentID    pgtype.Text        `json:"payment_id"`
	CouponCode   pgtype.Text        `json:"coupon_code"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}
