// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payment.sql

package sqlgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const attachCheckoutSessionID = `-- name: AttachCheckoutSessionID :one
UPDATE payments
SET checkout_session_id = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, checkout_session_id, session_code, amount_cents, currency, status, reveal_pin, reveal_expires_at, reveal_consumed_at, failure_code, failure_detail, created_at, updated_at
`

type AttachCheckoutSessionIDParams struct {
	ID                pgtype.UUID `json:"id"`
	CheckoutSessionID pgtype.Text `json:"checkout_session_id"`
}

func (q *Queries) AttachCheckoutSessionID(ctx context.Context, arg AttachCheckoutSessionIDParams) (Payment, error) {
	row := q.db.QueryRow(ctx, attachCheckoutSessionID, arg.ID, arg.CheckoutSessionID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.CheckoutSessionID,
		&i.SessionCode,
		&i.AmountCents,
		&i.Currency,
		&i.Status,
		&i.RevealPin,
		&i.RevealExpiresAt,
		&i.RevealConsumedAt,
		&i.FailureCode,
		&i.FailureDetail,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const consumePaymentReveal = `-- name: ConsumePaymentReveal :one
UPDATE payments
SET reveal_consumed_at = $2,
    updated_at = $2
WHERE id = $1
RETURNING id, checkout_session_id, session_code, amount_cents, currency, status, reveal_pin, reveal_expires_at, reveal_consumed_at, failure_code, failure_detail, created_at, updated_at
`

type ConsumePaymentRevealParams struct {
	ID               pgtype.UUID        `json:"id"`
	RevealConsumedAt pgtype.Timestamptz `json:"reveal_consumed_at"`
}

func (q *Queries) ConsumePaymentReveal(ctx context.Context, arg ConsumePaymentRevealParams) (Payment, error) {
	row := q.db.QueryRow(ctx, consumePaymentReveal, arg.ID, arg.RevealConsumedAt)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.CheckoutSessionID,
		&i.SessionCode,
		&i.AmountCents,
		&i.Currency,
		&i.Status,
		&i.RevealPin,
		&i.RevealExpiresAt,
		&i.RevealConsumedAt,
		&i.FailureCode,
		&i.FailureDetail,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPendingPayment = `-- name: CreatePendingPayment :one

INSERT INTO payments (amount_cents, currency, status)
VALUES ($1, $2, 'pending')
RETURNING id, checkout_session_id, session_code, amount_cents, currency, status, reveal_pin, reveal_expires_at, reveal_consumed_at, failure_code, failure_detail, created_at, updated_at
`

type CreatePendingPaymentParams struct {
	AmountCents int32  `json:"amount_cents"`
	Currency    string `json:"currency"`
}

// Queries for payments table.
func (q *Queries) CreatePendingPayment(ctx context.Context, arg CreatePendingPaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPendingPayment, arg.AmountCents, arg.Currency)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.CheckoutSessionID,
		&i.SessionCode,
		&i.AmountCents,
		&i.Currency,
		&i.Status,
		&i.RevealPin,
		&i.RevealExpiresAt,
		&i.RevealConsumedAt,
		&i.FailureCode,
		&i.FailureDetail,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentByCheckoutSessionID = `-- name: GetPaymentByCheckoutSessionID :one
SELECT id, checkout_session_id, session_code, amount_cents, currency, status, reveal_pin, reveal_expires_at, reveal_consumed_at, failure_code, failure_detail, created_at, updated_at FROM payments WHERE checkout_session_id = $1
`

func (q *Queries) GetPaymentByCheckoutSessionID(ctx context.Context, checkoutSessionID pgtype.Text) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByCheckoutSessionID, checkoutSessionID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.CheckoutSessionID,
		&i.SessionCode,
		&i.AmountCents,
		&i.Currency,
		&i.Status,
		&i.RevealPin,
		&i.RevealExpiresAt,
		&i.RevealConsumedAt,
		&i.FailureCode,
		&i.FailureDetail,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentByCheckoutSessionIDForUpdate = `-- name: GetPaymentByCheckoutSessionIDForUpdate :one
SELECT id, checkout_session_id, session_code, amount_cents, currency, status, reveal_pin, reveal_expires_at, reveal_consumed_at, failure_code, failure_detail, created_at, updated_at FROM payments WHERE checkout_session_id = $1 FOR UPDATE
`

func (q *Queries) GetPaymentByCheckoutSessionIDForUpdate(ctx context.Context, checkoutSessionID pgtype.Text) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByCheckoutSessionIDForUpdate, checkoutSessionID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.CheckoutSessionID,
		&i.SessionCode,
		&i.AmountCents,
		&i.Currency,
		&i.Status,
		&i.RevealPin,
		&i.RevealExpiresAt,
		&i.RevealConsumedAt,
		&i.FailureCode,
		&i.FailureDetail,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentByIDForUpdate = `-- name: GetPaymentByIDForUpdate :one
SELECT id, checkout_session_id, session_code, amount_cents, currency, status, reveal_pin, reveal_expires_at, reveal_consumed_at, failure_code, failure_detail, created_at, updated_at FROM payments WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetPaymentByIDForUpdate(ctx context.Context, id pgtype.UUID) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByIDForUpdate, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.CheckoutSessionID,
		&i.SessionCode,
		&i.AmountCents,
		&i.Currency,
		&i.Status,
		&i.RevealPin,
		&i.RevealExpiresAt,
		&i.RevealConsumedAt,
		&i.FailureCode,
		&i.FailureDetail,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markPaymentFailedByID = `-- name: MarkPaymentFailedByID :one
UPDATE payments
SET checkout_session_id = CASE
        WHEN $2 <> '' THEN COALESCE(checkout_session_id, $2)
        ELSE checkout_session_id
    END,
    status = 'failed',
    failure_code = $3,
    failure_detail = $4,
    updated_at = now()
WHERE id = $1
RETURNING id, checkout_session_id, session_code, amount_cents, currency, status, reveal_pin, reveal_expires_at, reveal_consumed_at, failure_code, failure_detail, created_at, updated_at
`

type MarkPaymentFailedByIDParams struct {
	ID            pgtype.UUID `json:"id"`
	Column2       interface{} `json:"column_2"`
	FailureCode   pgtype.Text `json:"failure_code"`
	FailureDetail pgtype.Text `json:"failure_detail"`
}

func (q *Queries) MarkPaymentFailedByID(ctx context.Context, arg MarkPaymentFailedByIDParams) (Payment, error) {
	row := q.db.QueryRow(ctx, markPaymentFailedByID,
		arg.ID,
		arg.Column2,
		arg.FailureCode,
		arg.FailureDetail,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.CheckoutSessionID,
		&i.SessionCode,
		&i.AmountCents,
		&i.Currency,
		&i.Status,
		&i.RevealPin,
		&i.RevealExpiresAt,
		&i.RevealConsumedAt,
		&i.FailureCode,
		&i.FailureDetail,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markPaymentPaidUnprovisionedByID = `-- name: MarkPaymentPaidUnprovisionedByID :one
UPDATE payments
SET checkout_session_id = CASE
        WHEN $2 <> '' THEN COALESCE(checkout_session_id, $2)
        ELSE checkout_session_id
    END,
    status = 'paid_unprovisioned',
    failure_code = NULL,
    failure_detail = NULL,
    updated_at = $3
WHERE id = $1
RETURNING id, checkout_session_id, session_code, amount_cents, currency, status, reveal_pin, reveal_expires_at, reveal_consumed_at, failure_code, failure_detail, created_at, updated_at
`

type MarkPaymentPaidUnprovisionedByIDParams struct {
	ID        pgtype.UUID        `json:"id"`
	Column2   interface{}        `json:"column_2"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) MarkPaymentPaidUnprovisionedByID(ctx context.Context, arg MarkPaymentPaidUnprovisionedByIDParams) (Payment, error) {
	row := q.db.QueryRow(ctx, markPaymentPaidUnprovisionedByID, arg.ID, arg.Column2, arg.UpdatedAt)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.CheckoutSessionID,
		&i.SessionCode,
		&i.AmountCents,
		&i.Currency,
		&i.Status,
		&i.RevealPin,
		&i.RevealExpiresAt,
		&i.RevealConsumedAt,
		&i.FailureCode,
		&i.FailureDetail,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markPaymentProvisionFailure = `-- name: MarkPaymentProvisionFailure :one
UPDATE payments
SET failure_code = $2,
    failure_detail = $3,
    updated_at = now()
WHERE checkout_session_id = $1
  AND status = 'paid_unprovisioned'
RETURNING id, checkout_session_id, session_code, amount_cents, currency, status, reveal_pin, reveal_expires_at, reveal_consumed_at, failure_code, failure_detail, created_at, updated_at
`

type MarkPaymentProvisionFailureParams struct {
	CheckoutSessionID pgtype.Text `json:"checkout_session_id"`
	FailureCode       pgtype.Text `json:"failure_code"`
	FailureDetail     pgtype.Text `json:"failure_detail"`
}

func (q *Queries) MarkPaymentProvisionFailure(ctx context.Context, arg MarkPaymentProvisionFailureParams) (Payment, error) {
	row := q.db.QueryRow(ctx, markPaymentProvisionFailure, arg.CheckoutSessionID, arg.FailureCode, arg.FailureDetail)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.CheckoutSessionID,
		&i.SessionCode,
		&i.AmountCents,
		&i.Currency,
		&i.Status,
		&i.RevealPin,
		&i.RevealExpiresAt,
		&i.RevealConsumedAt,
		&i.FailureCode,
		&i.FailureDetail,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markPaymentProvisioned = `-- name: MarkPaymentProvisioned :one
UPDATE payments
SET status = 'provisioned',
    session_code = $2,
    reveal_pin = $3,
    reveal_expires_at = $4,
    failure_code = NULL,
    failure_detail = NULL,
    updated_at = $5
WHERE id = $1
RETURNING id, checkout_session_id, session_code, amount_cents, currency, status, reveal_pin, reveal_expires_at, reveal_consumed_at, failure_code, failure_detail, created_at, updated_at
`

type MarkPaymentProvisionedParams struct {
	ID              pgtype.UUID        `json:"id"`
	SessionCode     pgtype.Text        `json:"session_code"`
	RevealPin       pgtype.Text        `json:"reveal_pin"`
	RevealExpiresAt pgtype.Timestamptz `json:"reveal_expires_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) MarkPaymentProvisioned(ctx context.Context, arg MarkPaymentProvisionedParams) (Payment, error) {
	row := q.db.QueryRow(ctx, markPaymentProvisioned,
		arg.ID,
		arg.SessionCode,
		arg.RevealPin,
		arg.RevealExpiresAt,
		arg.UpdatedAt,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.CheckoutSessionID,
		&i.SessionCode,
		&i.AmountCents,
		&i.Currency,
		&i.Status,
		&i.RevealPin,
		&i.RevealExpiresAt,
		&i.RevealConsumedAt,
		&i.FailureCode,
		&i.FailureDetail,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
