// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: report.sql

package sqlgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createReport = `-- name: CreateReport :one
INSERT INTO reports (session_code, status, content_en, content_es, strengths, weaknesses, recommendation, question_count, duration_minutes)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, session_code, status, content_en, content_es, strengths, weaknesses, recommendation, question_count, duration_minutes, created_at, updated_at
`

type CreateReportParams struct {
	SessionCode     string      `json:"session_code"`
	Status          string      `json:"status"`
	ContentEn       pgtype.Text `json:"content_en"`
	ContentEs       pgtype.Text `json:"content_es"`
	Strengths       []byte      `json:"strengths"`
	Weaknesses      []byte      `json:"weaknesses"`
	Recommendation  pgtype.Text `json:"recommendation"`
	QuestionCount   int32       `json:"question_count"`
	DurationMinutes int32       `json:"duration_minutes"`
}

func (q *Queries) CreateReport(ctx context.Context, arg CreateReportParams) (Report, error) {
	row := q.db.QueryRow(ctx, createReport,
		arg.SessionCode,
		arg.Status,
		arg.ContentEn,
		arg.ContentEs,
		arg.Strengths,
		arg.Weaknesses,
		arg.Recommendation,
		arg.QuestionCount,
		arg.DurationMinutes,
	)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.SessionCode,
		&i.Status,
		&i.ContentEn,
		&i.ContentEs,
		&i.Strengths,
		&i.Weaknesses,
		&i.Recommendation,
		&i.QuestionCount,
		&i.DurationMinutes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReportBySession = `-- name: GetReportBySession :one
SELECT id, session_code, status, content_en, content_es, strengths, weaknesses, recommendation, question_count, duration_minutes, created_at, updated_at FROM reports WHERE session_code = $1
`

func (q *Queries) GetReportBySession(ctx context.Context, sessionCode string) (Report, error) {
	row := q.db.QueryRow(ctx, getReportBySession, sessionCode)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.SessionCode,
		&i.Status,
		&i.ContentEn,
		&i.ContentEs,
		&i.Strengths,
		&i.Weaknesses,
		&i.Recommendation,
		&i.QuestionCount,
		&i.DurationMinutes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateReport = `-- name: UpdateReport :exec
UPDATE reports
SET status = $2,
    content_en = $3,
    content_es = $4,
    strengths = $5,
    weaknesses = $6,
    recommendation = $7,
    question_count = $8,
    duration_minutes = $9,
    updated_at = now()
WHERE session_code = $1
`

type UpdateReportParams struct {
	SessionCode     string      `json:"session_code"`
	Status          string      `json:"status"`
	ContentEn       pgtype.Text `json:"content_en"`
	ContentEs       pgtype.Text `json:"content_es"`
	Strengths       []byte      `json:"strengths"`
	Weaknesses      []byte      `json:"weaknesses"`
	Recommendation  pgtype.Text `json:"recommendation"`
	QuestionCount   int32       `json:"question_count"`
	DurationMinutes int32       `json:"duration_minutes"`
}

func (q *Queries) UpdateReport(ctx context.Context, arg UpdateReportParams) error {
	_, err := q.db.Exec(ctx, updateReport,
		arg.SessionCode,
		arg.Status,
		arg.ContentEn,
		arg.ContentEs,
		arg.Strengths,
		arg.Weaknesses,
		arg.Recommendation,
		arg.QuestionCount,
		arg.DurationMinutes,
	)
	return err
}
