// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: session.sql

package sqlgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimCoupon = `-- name: ClaimCoupon :one

UPDATE coupons SET current_uses = current_uses + 1
WHERE code = $1 AND current_uses < max_uses
AND (expires_at IS NULL OR expires_at > now())
RETURNING id, code, max_uses, current_uses, discount_pct, expires_at, source, created_at
`

// Queries for sessions + coupons tables.
// Used by sqlc to generate type-safe Go code in internal/sqlgen/.
// Atomically increment coupon usage. Returns the coupon if valid.
func (q *Queries) ClaimCoupon(ctx context.Context, code string) (Coupon, error) {
	row := q.db.QueryRow(ctx, claimCoupon, code)
	var i Coupon
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.MaxUses,
		&i.CurrentUses,
		&i.DiscountPct,
		&i.ExpiresAt,
		&i.Source,
		&i.CreatedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (session_code, pin_hash, coupon_code, status, expires_at)
VALUES ($1, $2, $3, 'created', $4)
RETURNING session_code, pin_hash, track, status, role, timer_seconds, started_at, ended_at, payment_id, coupon_code, expires_at, created_at
`

type CreateSessionParams struct {
	SessionCode string             `json:"session_code"`
	PinHash     string             `json:"pin_hash"`
	CouponCode  pgtype.Text        `json:"coupon_code"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.SessionCode,
		arg.PinHash,
		arg.CouponCode,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.SessionCode,
		&i.PinHash,
		&i.Track,
		&i.Status,
		&i.Role,
		&i.TimerSeconds,
		&i.StartedAt,
		&i.EndedAt,
		&i.PaymentID,
		&i.CouponCode,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSessionByCode = `-- name: GetSessionByCode :one
SELECT session_code, pin_hash, track, status, role, timer_seconds, started_at, ended_at, payment_id, coupon_code, expires_at, created_at FROM sessions WHERE session_code = $1
`

func (q *Queries) GetSessionByCode(ctx context.Context, sessionCode string) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByCode, sessionCode)
	var i Session
	err := row.Scan(
		&i.SessionCode,
		&i.PinHash,
		&i.Track,
		&i.Status,
		&i.Role,
		&i.TimerSeconds,
		&i.StartedAt,
		&i.EndedAt,
		&i.PaymentID,
		&i.CouponCode,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const startSession = `-- name: StartSession :one
UPDATE sessions SET status = 'interviewing', started_at = now()
WHERE session_code = $1 AND status = 'created'
RETURNING session_code, pin_hash, track, status, role, timer_seconds, started_at, ended_at, payment_id, coupon_code, expires_at, created_at
`

// Atomically transition session to interviewing. Only succeeds if status is 'created'.
func (q *Queries) StartSession(ctx context.Context, sessionCode string) (Session, error) {
	row := q.db.QueryRow(ctx, startSession, sessionCode)
	var i Session
	err := row.Scan(
		&i.SessionCode,
		&i.PinHash,
		&i.Track,
		&i.Status,
		&i.Role,
		&i.TimerSeconds,
		&i.StartedAt,
		&i.EndedAt,
		&i.PaymentID,
		&i.CouponCode,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
