// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: session.sql

package sqlgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimCoupon = `-- name: ClaimCoupon :one

UPDATE coupons SET current_uses = current_uses + 1
WHERE code = $1 AND current_uses < max_uses
AND (expires_at IS NULL OR expires_at > now())
RETURNING id, code, max_uses, current_uses, discount_pct, expires_at, source, created_at
`

// Queries for sessions + coupons tables.
// Used by sqlc to generate type-safe Go code in internal/sqlgen/.
// Atomically increment coupon usage. Returns the coupon if valid.
func (q *Queries) ClaimCoupon(ctx context.Context, code string) (Coupon, error) {
	row := q.db.QueryRow(ctx, claimCoupon, code)
	var i Coupon
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.MaxUses,
		&i.CurrentUses,
		&i.DiscountPct,
		&i.ExpiresAt,
		&i.Source,
		&i.CreatedAt,
	)
	return i, err
}

const completeSession = `-- name: CompleteSession :exec
UPDATE sessions SET status = 'completed', ended_at = now()
WHERE session_code = $1 AND status = 'interviewing'
`

// Marks an interviewing session as completed with ended_at = now().
func (q *Queries) CompleteSession(ctx context.Context, sessionCode string) error {
	_, err := q.db.Exec(ctx, completeSession, sessionCode)
	return err
}

const createCoupon = `-- name: CreateCoupon :one
INSERT INTO coupons (code, max_uses, source)
VALUES ($1, $2, $3)
RETURNING id, code, max_uses, current_uses, discount_pct, expires_at, source, created_at
`

type CreateCouponParams struct {
	Code    string      `json:"code"`
	MaxUses int32       `json:"max_uses"`
	Source  pgtype.Text `json:"source"`
}

func (q *Queries) CreateCoupon(ctx context.Context, arg CreateCouponParams) (Coupon, error) {
	row := q.db.QueryRow(ctx, createCoupon, arg.Code, arg.MaxUses, arg.Source)
	var i Coupon
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.MaxUses,
		&i.CurrentUses,
		&i.DiscountPct,
		&i.ExpiresAt,
		&i.Source,
		&i.CreatedAt,
	)
	return i, err
}

const createPaidSession = `-- name: CreatePaidSession :exec
INSERT INTO sessions (session_code, pin_hash, payment_id, status, expires_at, interview_budget_seconds)
VALUES ($1, $2, $3, 'created', $4, $5)
`

type CreatePaidSessionParams struct {
	SessionCode            string             `json:"session_code"`
	PinHash                string             `json:"pin_hash"`
	PaymentID              pgtype.Text        `json:"payment_id"`
	ExpiresAt              pgtype.Timestamptz `json:"expires_at"`
	InterviewBudgetSeconds int32              `json:"interview_budget_seconds"`
}

func (q *Queries) CreatePaidSession(ctx context.Context, arg CreatePaidSessionParams) error {
	_, err := q.db.Exec(ctx, createPaidSession,
		arg.SessionCode,
		arg.PinHash,
		arg.PaymentID,
		arg.ExpiresAt,
		arg.InterviewBudgetSeconds,
	)
	return err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (
    session_code,
    pin_hash,
    coupon_code,
    coupon_max_uses_at_claim,
    coupon_current_uses_at_claim,
    status,
    expires_at,
    interview_budget_seconds
)
VALUES ($1, $2, $3, $4, $5, 'created', $6, $7)
RETURNING session_code, pin_hash, track, status, role, ended_at, payment_id, coupon_code, expires_at, created_at, interview_budget_seconds, interview_lapsed_seconds, interview_lapsed_updated_at, interview_started_at, current_interview_started_at, last_api_call_at, conversation_history, preferred_language, flow_step, expected_turn_id, display_question_number, active_question_text_es, active_question_text_en, active_question_area, active_question_kind, active_question_issued_at, active_answer_deadline_at, coupon_max_uses_at_claim, coupon_current_uses_at_claim
`

type CreateSessionParams struct {
	SessionCode              string             `json:"session_code"`
	PinHash                  string             `json:"pin_hash"`
	CouponCode               pgtype.Text        `json:"coupon_code"`
	CouponMaxUsesAtClaim     pgtype.Int4        `json:"coupon_max_uses_at_claim"`
	CouponCurrentUsesAtClaim pgtype.Int4        `json:"coupon_current_uses_at_claim"`
	ExpiresAt                pgtype.Timestamptz `json:"expires_at"`
	InterviewBudgetSeconds   int32              `json:"interview_budget_seconds"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.SessionCode,
		arg.PinHash,
		arg.CouponCode,
		arg.CouponMaxUsesAtClaim,
		arg.CouponCurrentUsesAtClaim,
		arg.ExpiresAt,
		arg.InterviewBudgetSeconds,
	)
	var i Session
	err := row.Scan(
		&i.SessionCode,
		&i.PinHash,
		&i.Track,
		&i.Status,
		&i.Role,
		&i.EndedAt,
		&i.PaymentID,
		&i.CouponCode,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.InterviewBudgetSeconds,
		&i.InterviewLapsedSeconds,
		&i.InterviewLapsedUpdatedAt,
		&i.InterviewStartedAt,
		&i.CurrentInterviewStartedAt,
		&i.LastApiCallAt,
		&i.ConversationHistory,
		&i.PreferredLanguage,
		&i.FlowStep,
		&i.ExpectedTurnID,
		&i.DisplayQuestionNumber,
		&i.ActiveQuestionTextEs,
		&i.ActiveQuestionTextEn,
		&i.ActiveQuestionArea,
		&i.ActiveQuestionKind,
		&i.ActiveQuestionIssuedAt,
		&i.ActiveAnswerDeadlineAt,
		&i.CouponMaxUsesAtClaim,
		&i.CouponCurrentUsesAtClaim,
	)
	return i, err
}

const getSessionByCode = `-- name: GetSessionByCode :one
SELECT session_code, pin_hash, track, status, role, ended_at, payment_id, coupon_code, expires_at, created_at, interview_budget_seconds, interview_lapsed_seconds, interview_lapsed_updated_at, interview_started_at, current_interview_started_at, last_api_call_at, conversation_history, preferred_language, flow_step, expected_turn_id, display_question_number, active_question_text_es, active_question_text_en, active_question_area, active_question_kind, active_question_issued_at, active_answer_deadline_at, coupon_max_uses_at_claim, coupon_current_uses_at_claim FROM sessions WHERE session_code = $1
`

func (q *Queries) GetSessionByCode(ctx context.Context, sessionCode string) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByCode, sessionCode)
	var i Session
	err := row.Scan(
		&i.SessionCode,
		&i.PinHash,
		&i.Track,
		&i.Status,
		&i.Role,
		&i.EndedAt,
		&i.PaymentID,
		&i.CouponCode,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.InterviewBudgetSeconds,
		&i.InterviewLapsedSeconds,
		&i.InterviewLapsedUpdatedAt,
		&i.InterviewStartedAt,
		&i.CurrentInterviewStartedAt,
		&i.LastApiCallAt,
		&i.ConversationHistory,
		&i.PreferredLanguage,
		&i.FlowStep,
		&i.ExpectedTurnID,
		&i.DisplayQuestionNumber,
		&i.ActiveQuestionTextEs,
		&i.ActiveQuestionTextEn,
		&i.ActiveQuestionArea,
		&i.ActiveQuestionKind,
		&i.ActiveQuestionIssuedAt,
		&i.ActiveAnswerDeadlineAt,
		&i.CouponMaxUsesAtClaim,
		&i.CouponCurrentUsesAtClaim,
	)
	return i, err
}

const startSession = `-- name: StartSession :one
UPDATE sessions
SET status = 'interviewing',
    interview_started_at = COALESCE(interview_started_at, now()),
    current_interview_started_at = now(),
    preferred_language = COALESCE(preferred_language, $2)
WHERE session_code = $1
  AND status IN ('created', 'active', 'interviewing')
RETURNING session_code, pin_hash, track, status, role, ended_at, payment_id, coupon_code, expires_at, created_at, interview_budget_seconds, interview_lapsed_seconds, interview_lapsed_updated_at, interview_started_at, current_interview_started_at, last_api_call_at, conversation_history, preferred_language, flow_step, expected_turn_id, display_question_number, active_question_text_es, active_question_text_en, active_question_area, active_question_kind, active_question_issued_at, active_answer_deadline_at, coupon_max_uses_at_claim, coupon_current_uses_at_claim
`

type StartSessionParams struct {
	SessionCode       string      `json:"session_code"`
	PreferredLanguage pgtype.Text `json:"preferred_language"`
}

// Idempotent session start for reconnects. Sets interview_started_at on first call,
// resets current_interview_started_at on every call. Accepts created, active, or interviewing.
// preferred_language is only set once (on first start), then remains locked.
func (q *Queries) StartSession(ctx context.Context, arg StartSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, startSession, arg.SessionCode, arg.PreferredLanguage)
	var i Session
	err := row.Scan(
		&i.SessionCode,
		&i.PinHash,
		&i.Track,
		&i.Status,
		&i.Role,
		&i.EndedAt,
		&i.PaymentID,
		&i.CouponCode,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.InterviewBudgetSeconds,
		&i.InterviewLapsedSeconds,
		&i.InterviewLapsedUpdatedAt,
		&i.InterviewStartedAt,
		&i.CurrentInterviewStartedAt,
		&i.LastApiCallAt,
		&i.ConversationHistory,
		&i.PreferredLanguage,
		&i.FlowStep,
		&i.ExpectedTurnID,
		&i.DisplayQuestionNumber,
		&i.ActiveQuestionTextEs,
		&i.ActiveQuestionTextEn,
		&i.ActiveQuestionArea,
		&i.ActiveQuestionKind,
		&i.ActiveQuestionIssuedAt,
		&i.ActiveAnswerDeadlineAt,
		&i.CouponMaxUsesAtClaim,
		&i.CouponCurrentUsesAtClaim,
	)
	return i, err
}
